package com.example.raajesharunachalam.communityserviceconnector;

import android.os.Parcel;
import android.os.Parcelable;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * Represents an individual Community Service/Volunteering Event and all of its necessary data to be
 * displayed to users of the app
 * <p>
 * Created by raajesharunachalam on 4/9/17.
 *
 * @author arnchlm2
 */

public class Event implements Parcelable {
    
    //Constants for use in reading and writing Event objects to the Firebase Database
    public static final String DESCRIPTION_KEY = "Description";
    public static final String ADDRESS_KEY = "Address";
    public static final String START_DATE_KEY = "Start Date";
    public static final String START_TIME_KEY = "Start Time";
    public static final String END_DATE_KEY = "End Date";
    public static final String END_TIME_KEY = "End Time";
    public static final String LATITUDE_KEY = "Latitude";
    public static final String LONGITUDE_KEY = "Longitude";
    public static final String PEOPLE_INTERESTED_KEY = "People Interested";
    public static final String NO_PEOPLE_INTERESTED_VALUE = "None";
    public static final String EVENT_LINK = "Event Link";
    public static final String EVENT_LINK_DEFAULT = "None";
    public static final String IMAGE_URL_KEY = "Image URL";
    public static final String IMAGE_URL_DEFAULT_LINK = "https://anca.org/wp-content/uploads/2015/" +
            "01/volunteer-logo-300x300.jpg";

    private String title;
    private String description;
    private String address;
    private String startDate;
    private String startTime;
    private String endDate;
    private String endTime;
    private String eventLink;
    private double latitude;
    private double longitude;
    private HashMap<String, String> peopleInterested;
    private String imageURL;

    public Event() {

    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public HashMap<String, String> getPeopleInterested() {
        return peopleInterested;
    }

    public void setPeopleInterested(HashMap<String, String> peopleInterested) {
        this.peopleInterested = peopleInterested;
    }

    public String getEventLink() {
        return eventLink;
    }

    public void setEventLink(String eventLink) {
        this.eventLink = eventLink;
    }

    public String getImageURL() {
        return imageURL;
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    /**
     * All of the following code is auto-generated by the Parcelable plugin for Android Studio. The
     * following code implements the Parcelable interface and associated methods for this class.
     */

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.title);
        dest.writeString(this.description);
        dest.writeString(this.address);
        dest.writeString(this.startDate);
        dest.writeString(this.startTime);
        dest.writeString(this.endDate);
        dest.writeString(this.endTime);
        dest.writeString(this.eventLink);
        dest.writeDouble(this.latitude);
        dest.writeDouble(this.longitude);
        dest.writeSerializable(this.peopleInterested);
        dest.writeString(this.imageURL);
    }

    protected Event(Parcel in) {
        this.title = in.readString();
        this.description = in.readString();
        this.address = in.readString();
        this.startDate = in.readString();
        this.startTime = in.readString();
        this.endDate = in.readString();
        this.endTime = in.readString();
        this.eventLink = in.readString();
        this.latitude = in.readDouble();
        this.longitude = in.readDouble();
        this.peopleInterested = (HashMap<String, String>) in.readSerializable();
        this.imageURL = in.readString();
    }

    public static final Creator<Event> CREATOR = new Creator<Event>() {
        @Override
        public Event createFromParcel(Parcel source) {
            return new Event(source);
        }

        @Override
        public Event[] newArray(int size) {
            return new Event[size];
        }
    };
}
